### ISSUE TITLE
Video im Start-Menü läd nicht

### ISSUE THREAD

**Issue by FlorianMM** [p-seminar-hsg/P-Seminar-Projekt#73]
Das hatten wir ja schon öfter, also wenns bei euch geht würde ich da jetzt nichts ändern, aber wenn ihr auch kein Video habt sollten wir was ändern xD

**Comment by lukellmann** [comment]
Rene hat das Video gelöscht (vielleicht versehentlich).
Ich lade es mit meinem nächsten Commit wieder hoch, dann sollte alles wieder funktionieren.
