### ISSUE TITLE
Teleporter und Itemsounds

### ISSUE THREAD

**Issue by FlorianMM** [p-seminar-hsg/P-Seminar-Projekt#74]
Der Teleportersound gefällt mir überhaupt nicht, kann Geschmackssache sein, aber vielleicht mag da ja noch jemand anderes seinen Senf zu abgeben. Mir schwebt da mehr so ein Sci-Fi warp vor... Bei den Sounds vom Herz würde ich nur einen Sound machen und nicht 3 verschiedene, dass klingt ziemlich schräg, wenn man mehrere auf einmal einsammelt. Aber was denkt ihr dazu?

**Comment by lukellmann** [comment]
Wenn du einen anderen Sound raussuchst, kann ich das gerne ändern.

Zu den Powerups:
Ich muss mir das nochmal anschauen, ob und wie ich jedem Item einen eigenen Sound zuordnen kann. Bisher wird halt für egal welches Item ein zufällige Item Sound abgespielt.

**Comment by FlorianMM** [comment]
> Wenn du einen anderen Sound raussuchst, kann ich das gerne ändern.

Ich hatte an sowas hier gedacht: https://motionarray.com/sound-effects/teleportation-in-games-96008
Der dritte gefällt mir am besten. Was hältst du davon?

**Comment by FlorianGanserFG** [comment]
Top


FlorianMM <notifications@github.com> schrieb am Sa., 23. Nov. 2019, 21:07:

**Comment by lukellmann** [comment]
Schau ich mir morgen an, bin erst dann wieder daheim, ist aber easy abgeändert.

**Comment by FlorianMM** [comment]
> Schau ich mir morgen an, bin erst dann wieder daheim, ist aber easy abgeändert.

Perfekt, danke! :-)

**Comment by lukellmann** [comment]
Der neue Teleporter Sound ist drin (der den du meintest, also der 3.).
Der Item-Sound ist jetzt auch einheitlich.

**Comment by lukellmann** [comment]
Der neue Teleporter Sound ist drin (der den du meintest, also der 3.).
Der Item-Sound ist jetzt auch einheitlich.
