### ISSUE TITLE
BossEnemy spawned Projectiles außerhalb der Map

### ISSUE THREAD

**Issue by FlorianMM** [p-seminar-hsg/P-Seminar-Projekt#90]
Wenn der Boss nah oben an der Wand steht, dann spawnen seine Geschosse teilweise außerhalb der Map. Keine Ahnung, wie man das verhindert, vielleicht über Tilemap.getBounds oder so, wäre nett, wenn du dir das mal anschaust Rene!

**Comment by lukellmann** [comment]
Da Rene vorhin einen Commit rausgehauen hat, bei dem er das Problem angegangen hat, schließe ich dieses Issue mal.
